### ISSUE TITLE
support rubocop-performance gem

### ISSUE THREAD

**Issue by modosc** [codeclimate/codeclimate-rubocop#166]
```
Performance Cops will be removed from RuboCop 0.68. Use rubocop-performance gem instead.

Put this in your Gemfile.

  gem 'rubocop-performance'

And then execute:

  $ bundle install

Put this into your .rubocop.yml.

  require: rubocop-performance

More information: https://github.com/rubocop-hq/rubocop-performance
```

**Comment by wfleming** [comment]
Please see #164 and #165. The stable version of this plugin is on an older version of RuboCop (0.52.1), so the stable version of this plugin will probably not be updated to use the gem because it isn't very relevant to that version.

If you want to use the separate gem with newer versions of RuboCop, please update to the `rubocop-0-67` channel as discussed at #164. But also note that for `0.67` you don't need to use separately require the performance gem yet: they're still builtin to RuboCop until `0.68`.

**Comment by modosc** [comment]
thanks @wfleming - i understand that piece. we get a warning every time we run rubocop 0.67.2 locally though - the only way to make it go away is to install that gem as described, but doing that breaks on codeclimate because the gem's not installed remotely.

**Comment by wfleming** [comment]
@modosc are you using the `rubocop-0-67` channel of the plugin? That channel does have the `rubocop-performance` gem install.

**Comment by modosc** [comment]
oops - you are totally right, i assumed it wasn't because of #165 but i just tried and it works. thanks!
