### ISSUE TITLE
Configure custom rubocop.yml file

### ISSUE THREAD

**Issue by ivdma** [codeclimate/codeclimate-rubocop#39]
couldn't figure out how to set a path to a custom rubocop.yml file. Is it undocumented or is it broken? This is my config:

```
---
engines:
  rubocop:
    enabled: true
    config: '.custom_rubocop.yml'
```

**Comment by driv3r** [comment]
we have our own `.rubocop.yml` file within the project, but doesn't quite work.

Also just an idea, it would probably make sense to merge `.rubocop.yml` file from project (i.e. with custom rules, but not all of them) with `.rubocop.yml` file from engine for a fallback. What do you think?

**Comment by wfleming** [comment]
First, I apologize to both of you for how long it's taken us to get back to you on these issues.

@ivdma We do support an alternative rubocop config file, and your config looks correct to me (and a similar one worked for me locally). Is this still not working for you? If not, are you using the CLI or locally or running analysis on codeclimate.com? If you're using the CLI, the first thing I would try is running `codeclimate engines:install`: you may still have an older version of the engine from before this functionality was added.

@driv3r What about your own `.rubocop.yml` doesn't seem to be quite working?

Right now, we don't support importing one config file into another: normally when people want to do this, they're importing from something outside of the checked-in repo, which doesn't usually work because of how we isolate running engines. I'm hesitant to automatically merge Code Climate's default Rubocop rules into a checked-in `.rubocop.yml` since if we tweaked our default rules (which we do sometimes), that would change analysis results, which would be surprising & undesirable for many people who have customized their own `.rubocop.yml`.

We do hope to eventually support importing base config files via Rubocop's `inherit_from` config directive, and I think importing our default rules explicitly that way would be the way to do it, but we haven't figured out a good way to do it yet that doesn't break aspects of the limits we place on engines for security reasons.

**Comment by driv3r** [comment]
@wfleming 

- I had only `.rubocop.yml`  file with out custom cops, but it didn't work (both on CC and locally with `codeclimate analyze`
- I've tried adding it as config option as @ivdma but with `codeclimate analyze` it didn't worked as well
- I've also tried changing name of the config file, without result

so currently I don't know any way of changing this config

**Comment by wfleming** [comment]
@driv3r Would you mind sharing your `.rubocop.yml` & `.codeclimate.yml`? Feel free to email me at will@codeclimate.com if you'd rather not share those publicly. Thanks.

**Comment by dfaulken** [comment]
Running RuboCop from a custom config file isn't working for me either - everything's public so feel free to poke around - specifically [this build](https://codeclimate.com/github/umts/jobapps/pull/178) on [this PR](https://github.com/umts/jobapps/pull/179) doesn't seem to be producing any output at all.

I'm looking to do this because we have a few repositories, this one included, which use our own custom RuboCop cops. Our CodeClimate builds are failing because our RuboCop config file requires the cops. ([example](https://codeclimate.com/github/umts/jobapps/builds/38)) This works fine with our CI (Travis) because it bundles from our Gemfile and the cops are included in our gem, but CodeClimate doesn't do that.

That being said, even if it is possible to create a separate RuboCop config file and use it for CodeClimate builds, we would still need to maintain two nearly identical files, as we would simply remove the problematic `require`.

Provided we can get the build to work properly, is it possible to specify scripts which are run before any engines are run? In our case, the failing line is [right at the top of the file](https://github.com/umts/jobapps/blob/bca128e526c4ffd45d9fa4e5f47bbd7b11caa408/.rubocop.yml#L1), so it'd be neat if we could do something like:

```yml
before_script: "tail -n +3 .rubocop.yml > .codeclimate-rubocop.yml"
# ...
engines:
  rubocop:
    config: ".codeclimate-rubocop.yml"
```

This way, we could just maintain the one RuboCop config file and generate the custom file on-the-fly from that.

**Comment by RochesterinNYC** [comment]
Hi, apologies if I'm rehashing things, but I don't quite understand what the state of `.rubocop.yml` files are in relation to Code Climate's rubocop engine. 

For Bundler, we're trying to add a `.codeclimate.yml` file to the repo via this PR (bundler/bundler/pull#4229) so that we can specify `exclude_paths`. This is the intended `.codeclimate.yml` file:

```
---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - "**.rb"
  - "bin/*"
  - "exe/*"
exclude_paths:
- bundler.gemspec
- "*.md"
- lib/bundler/ssl_certs/*.pem
- lib/bundler/vendor/**/*
- lib/bundler/templates/**/*.tt
- man/*
- spec/**/*
```

Adding this file has the side effect of causing the Rubocop engine on Code Climate to detect 28 new violations (https://codeclimate.com/github/bundler/bundler/pull/4229). We have a `.rubocop.yml` file (https://github.com/bundler/bundler/blob/master/.rubocop.yml) that uses `inherit_from` on a `.rubocop_todo.yml` file (https://github.com/bundler/bundler/blob/master/.rubocop_todo.yml) that has all these 28 "new" violations excluded. 

Shouldn't the Code Climate Rubocop engine be:

- using our repo's `.rubocop.yml` configuration
- picking up the additional `.rubocop_todo.yml` via the `inherit_from` in `.rubocop.yml`
- excluding these violations in its analysis
- and then not reporting these violations?

If this should be a separate issue and not tacked onto this current issue, please let me know and I will move this over to a new issue.

**Comment by KevinBongart** [comment]
@wfleming, re: https://github.com/codeclimate/codeclimate/pull/308#issuecomment-175284874

I tried a couple of things on a large codebase:

1. When `.rubocop.yml` inherits from `.rubocop_todo.yml`:
  - `codeclimate analyze -e rubocop`: Found 155 issues
  - `rubocop`: no offenses detected
2. When `.rubocop.yml` doesn't inherit from `.rubocop_todo.yml`:
  - `codeclimate analyze -e rubocop`: Found 3,299 issues
  - `rubocop`: 3834 offenses detected

There are some paths excluded for all engines in `.codeclimate.yml` (which explains some differences in 2.), but no specific configuration for the rubocop engine.

I'd love to pin down where these 155 issues come from: ideally, it should be 0 just like when I run `rubocop` manually.

1. I thought Code Climate was not letting Rubocop inherit from another Rubocop config file? It looks like it is working
2. Would it be possible to pass in Rubocop params? For instance, `rubocop --display-cop-names` could be very useful
3. What can I do to help identifying what's happening here?

**Comment by pbrisbin** [comment]
Hi @KevinBongart 

> I thought Code Climate was not letting Rubocop inherit from another Rubocop config file? It looks like it is working

I think we were misunderstanding `inherit_from` a bit and I apologize for the confusion. It's common for users to use `inherit_from: ~/.rubocop.yml` and that we can't support. Our analysis runs on a fresh clone and cannot access anything outside of the project root. We conflated that to mean "we don't support `inherit_from`", which may not be true. In fact, given your testing it seems to work provided the file from which you're inheriting is also within the project root.

> Would it be possible to pass in Rubocop params? For instance, rubocop --display-cop-names could be very useful

This is not directly supported in the CLI, but depending on what you're trying to do you might have success running the engine image directly:

```
docker run --rm --volume $PWD:/code codeclimate/codeclimate-rubocop rubocop --display-cop-names
```

seems to have worked for me.

> Could this come from different Rubocop versions between my Gemfile and the CC engine?

That's my best guess. It looks like the current version on DockerHub is 0.35.1

```
% docker run --rm codeclimate/codeclimate-rubocop rubocop --version                                  codeclimate-rubocop:master
warning: parser/current is loading parser/ruby22, which recognizes
warning: 2.2.3-compliant syntax, but you are running 2.2.2.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
0.35.1
```

Would it be possible for you to run that version of rubocop directly and see if it finds the same 155 issues `codeclimate analyze` does?

> What can I do to help identifying what's happening here?

You're doing it! Your engagement in this Issue has been super helpful. It's also possible that the trick of running commands in the engine image directly is useful to figure things out.

**Comment by KevinBongart** [comment]
Thanks for your help @pbrisbin! I downgraded from the newest Rubocop 0.36.0 to CC's 0.35.1 and got this interesting output:

```bash
$ rubocop -v
0.35.1

$ rubocop   
Warning: unrecognized cop Lint/IneffectiveAccessModifier found in .rubocop_todo.yml
.rubocop.yml: Style/SpaceBeforeFirstArg has the wrong namespace - should be Lint
Warning: unrecognized cop Rails found in .rubocop.yml
[…]
666 files inspected, 140 offenses detected
```

I'm assuming the issue is due to some cops that have been renamed (looks like a lot of them come from `Style/SpaceBeforeFirstArg` or from cops config that didn't exist in 0.35.1). Getting closer to that 155 offenses detected by CC (could be an exclude path difference between Rubocop and CC).

What's blocking CC to upgrade rubocop?

**Comment by pbrisbin** [comment]
> Getting closer to that 155 offenses detected by CC (could be an exclude path difference between Rubocop and CC).

That's good news. Would you consider the behavior your seeing sufficiently explained then?

> What's blocking CC to upgrade rubocop?

Generally speaking, and as you've just seen, there are some compatibility concerns. If we ship a new engine on the updated rubcop, it will likely error many users' analyses because of the renamed and removed cops that are still present in their configs. We do plan to upgrade soon (I think there's even a PR that does it), but we're taking some time to fully consider the impact that'll have on these users.

**Comment by KevinBongart** [comment]
Yes, we'll just wait for this Rubocop upgrade before migrating to the new CC platform then. Thanks for the explanation!

**Comment by jhubert** [comment]
Same issue here, although I've already migrated all of my code to the latest rubocop and now it's throwing issues all over code climate.

**Comment by KevinBongart** [comment]
@pbrisbin I understand people have different versions of Rubocop, and upgrading often introduces new issues (code or configuration-related). I'm guessing it should be the user's responsibility to fix these, but on their own schedule.

The main CC engine could import different versions of the Rubocop engine (each built with a specific gem version), depending on the user configuration, and default to the latest one.

(I believe the engine has to be built with a specific gem and can't just switch gemfiles on the go?)

**Comment by jpignata** [comment]
@KevinBongart Yeah, that's correct, at the moment. We're going to add support for either a configurable version of RuboCop or a configurable version of the codeclimate engine. W're going to be deploying master of the engine which includes the latest version of RuboCop shortly.

**Comment by KevinBongart** [comment]
Nice to see codeclimate-rubocop is now using the latest Rubocop version! :+1: 

I updated to CC 0.20.0 and got 26 issues, the first one for instance:

```bash
codeclimate analyze -e rubocop

[…]

== app/models/cycle_count_request.rb (1 issue) ==
44: Do not use `Time.parse` without zone. Use one of `Time.zone.parse`, `Time.current`, `Time.parse.in_time_zone`, `Time.parse.utc`, `Time.parse.getlocal`, `Time.parse.iso8601`, `Time.parse.jisx0301`, `Time.parse.rfc3339`, `Time.parse.to_i`, `Time.parse.to_f` instead. [rubocop]
```

even though in my `.rubocop_todo.yml`:

```yml
Rails/TimeZone:
  Exclude:
    - 'a_file'
    - 'app/models/cycle_count_request.rb'
    - 'another_file'
```

and:

```
rubocop --only Rails/TimeZone               
Inspecting 668 files
668 files inspected, no offenses detected
```

Interestingly, about 14 offenses from that same TimeZone cop but from other files (excluded in the config above) aren't picked up by CC. But they *are* picked up by both CC and Rubocop when I comment out this `Exclude:` config though.

Let me know how I can help!

**Comment by KevinBongart** [comment]
@wfleming #51 fixed it, thanks!

```
codeclimate analyze -e rubocop
Starting analysis
Running rubocop: Done!

Analysis complete! Found 0 issues.
```

:tada: :balloon: :clap:

**Comment by wfleming** [comment]
@KevinBongart I was just typing up a comment here to ask you to check if that fixed your problem! Thanks for letting us know.

**Comment by emaiax** [comment]
Rubocop's `TargetRubyVersion: 2.3` doesn't seem to be considered by analysis though.

Or am I missing something? :confounded:

**Comment by jpignata** [comment]
@emaiax We should be passing the target ruby version along in our engine. Are you seeing different analysis results locally versus via Code Climate (either through the CLI or site)?

**Comment by emaiax** [comment]
@jpignata actually, yeah.

Rubocop's results differs from Code Climate's results and it's just because the configuration `TargetRubyVersion`.

**Comment by jpignata** [comment]
@emaiax Hmm, bummer. Can you send me a quick gist with what's being flagged differently so I can poke into it?

**Comment by emaiax** [comment]
@jpignata here's the [gist](https://gist.github.com/emaiax/7432638f8341804c9097) with some results. Apparently, rubocop gives me the same results whether using `TargetRubyVersion` or not.

I'm kinda lost here. :/

**Comment by jpignata** [comment]
@emaiax I think the bug is that we're disregarding `StyleGuideCopsOnly` in your configuration. If I change the `TargetRubyVersion` to 2.2, the issue isn't reported via the Code Climate CLI, and if I remove `StyleGuideCopsOnly`, the issue does get reported via `rubocop`. Does that make sense?

**Comment by emaiax** [comment]
@jpignata yeah, that doesn't make too much sense to me. Shouldn't they be the same?

**Comment by jpignata** [comment]
@emaiax Yeah, looks like a bug in the RuboCop engine. I'd expect the engine to honor the `StyleGuideCopsOnly` declaration.

**Comment by emaiax** [comment]
@jpignata does this [line](https://github.com/codeclimate/codeclimate-rubocop/blob/master/config/style_guides/ruby.yml#L23) have something to do with it?

using standalone rubocop, he respects the `StyleGuideCopsOnly` declaration, but codeclimate cli doesn't.

**Comment by jpignata** [comment]
@emaiax Sorry for being unclear. It's a bug in the Code Climate RuboCop engine. RuboCop's runner has some logic around selecting the right cops for a team based upon the configuration that our engine does not implement. We'll need to fix this in the engine to honor the `StyleGuideCopsOnly` attribute. See https://github.com/bbatsov/rubocop/blob/master/lib/rubocop/runner.rb#L226 for what RuboCop does and https://github.com/codeclimate/codeclimate-rubocop/blob/master/lib/cc/engine/source_file.rb#L32 for what the Code Climate engine does.

Until we fix this bug, it might be best to disable the cops you don't expect to see explicitly.

**Comment by emaiax** [comment]
@jpignata oh, ok, now I get it. I'm looking forward to see this. Thanks, man! :dancers:

**Comment by jpignata** [comment]
I added https://github.com/codeclimate/codeclimate-rubocop/issues/59 to address the issue above. Please re-open if there are other issues in this thread that aren't addressed or tracked separately.

**Comment by hoshy** [comment]
> Running RuboCop from a custom config file isn't working for me either - everything's public so feel free to poke around - specifically [this build](https://codeclimate.com/github/umts/jobapps/pull/178) on [this PR](https://github.com/umts/jobapps/pull/179) doesn't seem to be producing any output at all.
> 
> I'm looking to do this because we have a few repositories, the one cited above included, which use our own custom RuboCop cops. Our CodeClimate builds are failing because our RuboCop config file requires the cops. ([example](https://codeclimate.com/github/umts/jobapps/builds/38)) This works fine with our CI (Travis) because it bundles from our Gemfile and the cops are included in our gem, but CodeClimate doesn't do that.
> 
> That being said, even if it is doable to create a separate RuboCop config file and use it for CodeClimate builds, we would still need to maintain two nearly identical files, as we would simply remove the problematic `require`.
> 
> Provided we can get the build to work properly, is it possible to specify scripts which are run before any engines are run? In our case, the failing line is [right at the top of the file](https://github.com/umts/jobapps/blob/bca128e526c4ffd45d9fa4e5f47bbd7b11caa408/.rubocop.yml#L1), so it'd be neat if we could do something like:
> 
> ```yaml
> before_script: "tail -n +3 .rubocop.yml > .codeclimate-rubocop.yml"
> # ...
> engines:
>   rubocop:
>     config: ".codeclimate-rubocop.yml"
> ```
> 
> This way, we could just maintain the one RuboCop config file and generate the custom file on-the-fly from that.

Hi @dfaulken , have you found a solution for this?
